name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev
  workflow_dispatch: # Allows for manual triggering of the deploy

jobs:
  validate-terraform:
    name: Validate Terraform
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      # Validate Terraform configuration
      - name: Terraform Validate
        run: terraform validate

  deploy-terraform:
    if: github.event_name == 'workflow_dispatch' # Only run on manual trigger
    name: Deploy Terraform
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      # Apply Terraform (Placeholder for actual deployment)
      - name: Terraform Apply
        env:
          TF_VAR_master_password: ${{ secrets.DB_MASTER_PASSWORD }} # Inject secret from GitHub Secrets
        run: |
          terraform init
          terraform apply -auto-approve
