name: Deploy to Development

on:
  workflow_dispatch: # Manual trigger for development deployment

jobs:
  deploy-dev:
    name: Deploy to Development Environment
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      # Configure AWS credentials from GitHub Secrets
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Navigate to the dev environment
      - name: Change Directory to Development Environment
        run: cd terraform/environments/dev

      # Apply Terraform in the dev environment
      - name: Terraform Apply (Development)
        env:
          TF_VAR_master_password: ${{ secrets.DB_MASTER_PASSWORD_DEV }}
        run: |
          terraform init
          terraform plan -out=tfplan
          terraform apply -auto-approve tfplan
